### ISSUE TITLE
Escape curly brackets in translations

### ISSUE THREAD

**Issue by andrjfrks** [Panya/svelte-intl#16]
Is there a solution if I need to include curly brackets in my string and I don't want to interpret them as parameters?

I have some url inputs with query parameters (wrapped in curly brackets) and I want to make a description of them with svelte-intl.

This translation:
`inputDescription: "This value needs to include {orderNumber} parameter."`
is printed like this:
`This value needs to include undefined parameter.`

What I want to achieve is preserving curly brackets and text between them.
`This value needs to include {orderNumber} parameter.`

**Comment by Panya** [comment]
Hi, to achieve this you need to place `{orderNumber}` in single quotes, like:
```js
inputDescription: "This value needs to include '{orderNumber}' parameter."
```
